# Generated by Django 3.1.6 on 2021-03-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profileinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
