# Generated by Django 3.1.6 on 2021-03-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210302_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='height',
            field=models.FloatField(null=True),
        ),
    ]
