# Generated by Django 3.1.6 on 2021-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210302_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='disab_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='disab_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='disability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='middlename',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
