# Generated by Django 3.1.6 on 2021-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profileinfo_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='pro_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
