# Generated by Django 3.1.6 on 2021-03-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210313_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='pincode',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
