# Generated by Django 3.1.6 on 2021-03-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210313_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='pro_pic',
            field=models.FileField(blank=True, default='/media/profilr_pic/default.png', null=True, upload_to='profile_pic'),
        ),
    ]
