# Generated by Django 3.1.6 on 2021-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210313_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='pro_pic',
            field=models.FileField(blank=True, default='/default.png', null=True, upload_to='profile_pic'),
        ),
    ]
