# Generated by Django 3.1.6 on 2021-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210313_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20),
        ),
    ]
