# Generated by Django 3.1.6 on 2021-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210313_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
