# Generated by Django 3.1.6 on 2021-03-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210315_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profiledata',
        ),
    ]
