# Generated by Django 3.1.6 on 2021-03-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_delete_profiledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='pId',
            field=models.CharField(default='JB', max_length=10),
        ),
    ]
