# Generated by Django 3.1.6 on 2021-03-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210316_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Body_Type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Caste',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Complexion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Country_Of_Residence',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Diet',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Education',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Height',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Manglik',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Marital_Status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Mother_Tongue',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_Religion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_State',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
