# Generated by Django 3.1.6 on 2021-03-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20210316_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='p_age_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='p_age_min',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
