# Generated by Django 3.1.6 on 2021-03-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20210316_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='middlename',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
