# Generated by Django 3.1.6 on 2021-03-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_profileinfo_s_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='annual_income',
            field=models.CharField(blank=True, default='not specified', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='current_location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='education_detail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='occupation_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
