# Generated by Django 3.1.6 on 2021-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20210316_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='p_Occupation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
