# Generated by Django 3.1.6 on 2021-03-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_profileinfo_p_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='b_Group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='diet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='m_Tounge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='smoke',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
