# Generated by Django 3.1.6 on 2021-03-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20210316_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
