# Generated by Django 3.1.6 on 2021-03-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20210317_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Self', 'Self')], max_length=50, null=True),
        ),
    ]
