# Generated by Django 3.1.6 on 2021-03-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20210317_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='rashi',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
