# Generated by Django 3.1.6 on 2021-03-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20210320_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='time_birth',
            field=models.TimeField(null=True),
        ),
    ]
