# Generated by Django 3.1.6 on 2021-03-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_profileinfo_time_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='time_birth',
            new_name='birth_time',
        ),
    ]
