# Generated by Django 3.1.6 on 2021-03-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20210320_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='dob',
        ),
    ]
