# Generated by Django 3.1.6 on 2021-03-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_remove_profileinfo_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
