# Generated by Django 3.1.6 on 2021-03-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_profileinfo_complexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='birth_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
