# Generated by Django 3.1.6 on 2021-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20210320_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='middlename',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
