# Generated by Django 3.1.6 on 2021-03-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20210320_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('mo_no', models.IntegerField()),
                ('msg', models.CharField(max_length=300)),
            ],
        ),
    ]
