# Generated by Django 3.1.6 on 2021-04-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_auto_20210408_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='country',
            field=models.CharField(blank=True, default=' ', max_length=250, null=True),
        ),
    ]
